https://daneden.github.io/animate.css/
http://cdn.bootcss.com/animate.css/3.5.2/ animate.min.css

Vue.config.devtools = true;
new Vue({
el: '#app',
data: {
message: 'hello world'
}
});
Vue.config.devtools = true;
https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd/related?hl=ja

https://cli.vuejs.org/

npm install --save-dev typescript ts-loader
https://qiita.com/isihigameKoudai/items/70c0cb93931cf508a53a

install node
https://qiita.com/kyosuke5_20/items/c5f68fc9d89b84c0df09

https://github.com/TypeStrong/ts-node
# Locally in your project.
npm install -D ts-node
npm install -D typescript

# Or globally with TypeScript.
npm install -g ts-node
npm install -g typescript

vue-cli 
https://qiita.com/atoris/items/6e603e59228f0ccadfd8
npm uninstall vue-cli -g
npm i -g yarn
yarn --version

yarn global add @vue/cli

https://www.te-nu.com/entry/2018/09/20/154714
環境：　https://qiita.com/reflet/items/16f90cbb0db68fd6a498
brew install nodebrew

npm install -g yarn
yarn install
 yarn upgrade ts-node@8.0.1
sudo npm i -g typescript

npm install -g @vue/cli

環境記事
https://cloudpack.media/43084

BROWSERSYNC
In Figure 1-1, the address that the browser was viewing was http://localhost:3000/. 
This means it was being served from a server at localhost port 3000. 
Since I didn’t deploy the index.html to a remote server or build a custom app to view it, 
  I was able to use Browsersync for hosting the files locally. Unless otherwise noted, 
    I will continue to use Browsersync ( https://www.browsersync.io/ ) for loading files during local development.

To install Browsersync, Node.js and NPM are required. The good news is that both are installed 
when you install Node.js. Node.js can be installed by following the directions at https://nodejs.org/ 
                                        
note.js.
https://qiita.com/kyosuke5_20/items/c5f68fc9d89b84c0df09
https://qiita.com/Alex_mht_code/items/422f5ce10d9c9d5729b7
                                        
# nodebrew setup時に打つと出てきたやつ
export PATH=/usr/local/var/nodebrew/current/bin:$PATH
export PATH=$HOME/.nodebrew/current/bin:$PATH

npm update -g npm
                                        
UI:
element:
https://element.eleme.io/#/en-US
https://github.com/ElemeFE/element
iview:
https://www.iviewui.com/
//LEARNING PATH: Build 7 Real World Applications with Vue.js
By Daniel Khalil, Jack Herrington and Rushabh Jadvani
//Beginning Vue.js
Gary JenningsAndrea Passaglia

//Hands-On Styling Vue.js Web Apps with Element UI and iView
Haider Rehman

官网 (PC 端)：https://nutui.jd.com

Github 仓库：https://github.com/jdf2e/nutui/

更新日志：https://github.com/jdf2e/nutui/releases

反馈建议：https://github.com/jdf2e/nutui/issues

NutUI 按需加载插件：
https://www.npmjs.com/package/@nutui/babel-plugin-separate-import

Vue 模板工程构建工具：https://www.npmjs.com/package/gaea-cli

不依赖 wifi 热点的 H5 真机测试工具 Carefree: https://carefree.jd.com/


https://www.getrevue.co/profile/vuenewsletter

UI example:
https://github.com/dmtrbrl/tmdb-app
https://www.jqwidgets.com/vue/?gclid=EAIaIQobChMIyNjSpIzt4AIVTzuWCh3bHgDpEAEYASAAEgI7UvD_BwE
https://vuejsexamples.com/tag/menu/

https://github.com/vuejs/awesome-vue
https://cn.vuejs.org/v2/guide/join.html

HTML5 video player
http://browserify.org/

vue hooks
https://www.getrevue.co/profile/vuenewsletter/issues/132-huge-improvement-in-new-vetur-release-go-and-get-linusborg-a-coffee-try-out-hooks-with-erik-hanchett-162011

https://www.vuemastery.com/pdf/Nuxtjs-Cheat-Sheet.pdf?utm_source=newsletter&utm_medium=email&utm_campaign=a_free_gift_from_vue_mastery&utm_term=2019-03-05

axios既提供了并发的封装，也没有fetch的各种问题，而且体积也较小，当之无愧现在最应该选用的请求的方式
https://jp.vuejs.org/v2/cookbook/using-axios-to-consume-apis.html
https://qiita.com/shisama/items/61cdcc09dc69fd8d3127
axiosというHTTPリクエストを行うためのライブラリがあります。
Node.js 7からasync/awaitを使えるようになりました。


VUE　chrome debug
https://chrome.google.com/webstore/search/vue
https://github.com/vuejs/vue-devtools
https://www.toutiao.com/a6646911001121784328/?tt_from=copy_link&utm_campaign=client_share&timestamp=1551188626&app=news_article&utm_source=copy_link&iid=59706816032&utm_medium=toutiao_ios&group_id=6646911001121784328

WEB books：
https://juejin.im/post/5c0098f66fb9a049dd80019e

教程：
https://www.jianshu.com/p/b396c86e4890

文档：
http://caibaojian.com/vue/

NutUI 2.0:
https://www.toutiao.com/a6662628293960794636/

资料
https://www.zhideedu.com/vue%20js%E5%AE%9E%E6%88%98%20pdf

app:
https://www.toutiao.com/a6634686140009939470/

webpack
http://webpack.wuhaolin.cn/
https://segmentfault.com/a/1190000009782174
https://juejin.im/entry/59b74efd51882532c85c835e
https://segmentfault.com/search?q=%E6%B7%B1%E5%85%A5%E6%B5%85%E5%87%BAwebpack%E5%AD%A6%E4%B9%A0

test:
https://segmentfault.com/a/1190000012940039

nuxt + firebase
https://qiita.com/redshoga/items/da5c0e247e0df314a257
https://qiita.com/potato4d/items/cfddeb8732fec63cb29c

https://inside.dmm.com/entry/2018/04/10/nuxt-firebase
https://inside.dmm.com/entry/2018/11/06/nuxt2-pwa-gae-se

https://yamitzky.hatenablog.com/entry/2018/12/10/232946
https://yamitzky.hatenablog.com/entry/2018/10/23/210924

next.js
https://tech.libinc.co.jp/entry/2018/11/15/143000

SPA
https://www.oro.com/ja/technology/001/

環境：
npm i -D webpack@latest
npm install webpack-dev-middleware --save-dev

npm view babel-eslint@7.* version
npm install --save-dev babel-eslint@7.2.3 
npm install webpack -g
npm install -D babel-loader @babel/core @babel/preset-env webpack

npm install -g npm-install-peers

npm install --save-dev mini-css-extract-plugin
npm i @angular/flex-layout@7.0.0-beta.22 --save
npm install -D babel-loader @babel/core @babel/preset-env webpack

npm install webpack@1.15.0 --save-dev && rm -rf node-modules && npm install

https://nodejs.org/en/
npm i
https://www.npmjs.com/package/npm-install-peers
npm install -g npm-install-peers

npm audit fix --force


https://qiita.com/mimikun/items/860bad42c9b5bd10c7f4
モジュールインストール

npm i -D electron
npm i -D react react-dom
npm i -D babel-core babel-preset-react babel-preset-env
npm i -D webpack babel-loader
npm i -D webpack-cli


