https://daneden.github.io/animate.css/
http://cdn.bootcss.com/animate.css/3.5.2/ animate.min.css



VUE　chrome debug
https://www.toutiao.com/a6646911001121784328/?tt_from=copy_link&utm_campaign=client_share&timestamp=1551188626&app=news_article&utm_source=copy_link&iid=59706816032&utm_medium=toutiao_ios&group_id=6646911001121784328

WEB books：
https://juejin.im/post/5c0098f66fb9a049dd80019e

教程：
https://www.jianshu.com/p/b396c86e4890

文档：
http://caibaojian.com/vue/

NutUI 2.0:
https://www.toutiao.com/a6662628293960794636/

资料
https://www.zhideedu.com/vue%20js%E5%AE%9E%E6%88%98%20pdf

app:
https://www.toutiao.com/a6634686140009939470/

webpack
http://webpack.wuhaolin.cn/
https://segmentfault.com/a/1190000009782174
https://juejin.im/entry/59b74efd51882532c85c835e
https://segmentfault.com/search?q=%E6%B7%B1%E5%85%A5%E6%B5%85%E5%87%BAwebpack%E5%AD%A6%E4%B9%A0
